services:
  app:
    build: .
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - "./data:/app/data"
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

  ui:
    build: ./time-zones-app
    ports:
      - "3000:3000"