services:
  app:
    build: .
    ports:
      - 5000:80
    volumes:
      - "./data:/app/data"
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  ui:
    build: ./time-zones-app
    ports:
      - "3000:3000"