version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: time-tracker-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - time-tracker-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: time-tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nV88XxSuVqW9sAKk

volumes:
  time-tracker-postgres:
