export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_RESET = 'AUTH_RESET';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'

export const AUTH_TRY_AUTO_SIGNUP = 'AUTH_TRY_AUTO_SIGNUP';

export const REFRESH_TOKEN_START = 'REFRESH_TOKEN_START';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const TIME_ZONES_GET = 'TIME_ZONES_GET';
export const TIME_ZONES_GET_START = 'TIME_ZONES_GET_START';
export const TIME_ZONES_GET_SUCCESS = 'TIME_ZONES_GET_SUCCESS';
export const TIME_ZONES_GET_FAIL = 'TIME_ZONES_GET_FAIL';

export const TIME_ZONE_EDIT = 'TIME_ZONE_EDIT';
export const TIME_ZONE_EDIT_START = 'TIME_ZONE_EDIT_START';
export const TIME_ZONE_EDIT_SUCCESS = 'TIME_ZONE_EDIT_SUCCESS';
export const TIME_ZONE_EDIT_FAIL = 'TIME_ZONE_EDIT_FAIL';

export const TIME_ZONE_LOADEDIT = 'TIME_ZONE_LOADEDIT';
export const TIME_ZONE_LOADEDIT_RESET = 'TIME_ZONE_LOADEDIT_RESET';
export const TIME_ZONE_LOADEDIT_START = 'TIME_ZONE_LOADEDIT_START';
export const TIME_ZONE_LOADEDIT_SUCCESS = 'TIME_ZONE_LOADEDIT_SUCCESS';
export const TIME_ZONE_LOADEDIT_FAIL = 'TIME_ZONE_LOADEDIT_FAIL';

export const TIME_ZONE_DELETE = 'TIME_ZONE_DELETE';
export const TIME_ZONE_DELETE_START = 'TIME_ZONE_DELETE_START';
export const TIME_ZONE_DELETE_SUCCESS = 'TIME_ZONE_DELETE_SUCCESS';
export const TIME_ZONE_DELETE_FAIL = 'TIME_ZONE_DELETE_FAIL';

export const USERS_GET = 'USERS_GET';
export const USERS_GET_START = 'USERS_GET_START';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_FAIL = 'USERS_GET_FAIL';

export const USER_EDIT = 'USER_EDIT';
export const USER_EDIT_START = 'USER_EDIT_START';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAIL = 'USER_EDIT_FAIL';

export const USER_LOADEDIT = 'USER_LOADEDIT';
export const USER_LOADEDIT_RESET = 'USER_LOADEDIT_RESET';
export const USER_LOADEDIT_START = 'USER_LOADEDIT_START';
export const USER_LOADEDIT_SUCCESS = 'USER_LOADEDIT_SUCCESS';
export const USER_LOADEDIT_FAIL = 'USER_LOADEDIT_FAIL';

export const USER_DELETE = 'USER_DELETE';
export const USER_DELETE_START = 'USER_DELETE_START';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';