export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_RESET = 'AUTH_RESET';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'

export const AUTH_TRY_AUTO_SIGNUP = 'AUTH_TRY_AUTO_SIGNUP';

export const REFRESH_TOKEN_START = 'REFRESH_TOKEN_START';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const TIME_ZONES_GET = 'TIME_ZONES_GET';
export const TIME_ZONES_GET_START = 'TIME_ZONES_GET_START';
export const TIME_ZONES_GET_SUCCESS = 'TIME_ZONES_GET_SUCCESS';
export const TIME_ZONES_GET_FAIL = 'TIME_ZONES_GET_FAIL';