services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: time-tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nV88XxSuVqW9sAKk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  web:
    build:
      context: ./time-tracker-web
    ports:
      - 3000:3000

  backend:
    build:
      context: ./time-tracker-backend
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy